CREATE TABLE IF NOT EXISTS Persons (
    PersonID VARCHAR(9) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Department VARCHAR(50) NOT NULL,
    ProofID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PersonID),
    UNIQUE (PersonID)
);

CREATE TABLE IF NOT EXISTS Items (
    ItemID VARCHAR(9) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Status VARCHAR(50) NOT NULL,
    PRIMARY KEY (ItemID),
    UNIQUE (ItemID)
);

CREATE TABLE IF NOT EXISTS SurrenderedItems (
    ItemID VARCHAR(9) NOT NULL,
    DateFound DATETIME NOT NULL,
    LocationFound VARCHAR(50) NOT NULL,
    PersonID VARCHAR(9) NOT NULL,
    PRIMARY KEY (ItemID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (PersonID) REFERENCES Persons(PersonID)
);

CREATE TABLE IF NOT EXISTS ClaimedItems (
    ItemID VARCHAR(9) NOT NULL,
    DateClaimed DATETIME NOT NULL,
    PersonID VARCHAR(9) NOT NULL,
    PRIMARY KEY (ItemID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (PersonID) REFERENCES Persons(PersonID)
);

CREATE TABLE IF NOT EXISTS ReportedItems (
    ItemID VARCHAR(9) NOT NULL,
    DateLost DATETIME NOT NULL,
    LocationLost VARCHAR(50) NOT NULL,
    PersonID VARCHAR(9) NOT NULL,
    PRIMARY KEY (ItemID),
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID),
    FOREIGN KEY (PersonID) REFERENCES Persons(PersonID)
);