# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'claimPerson.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClaimPersonDialog(object):
    def setupUi(self, ClaimPersonDialog):
        ClaimPersonDialog.setObjectName("ClaimPersonDialog")
        ClaimPersonDialog.resize(600, 682)
        self.confirmButton = QtWidgets.QPushButton(ClaimPersonDialog)
        self.confirmButton.setGeometry(QtCore.QRect(360, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.confirmButton.setObjectName("confirmButton")
        self.phoneNumberEdit = QtWidgets.QLineEdit(ClaimPersonDialog)
        self.phoneNumberEdit.setGeometry(QtCore.QRect(11, 280, 271, 41))
        self.phoneNumberEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.phoneNumberEdit.setObjectName("phoneNumberEdit")
        self.cancelButton = QtWidgets.QPushButton(ClaimPersonDialog)
        self.cancelButton.setGeometry(QtCore.QRect(11, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton.setObjectName("cancelButton")
        self.departmentEdit = QtWidgets.QLineEdit(ClaimPersonDialog)
        self.departmentEdit.setGeometry(QtCore.QRect(300, 280, 271, 41))
        self.departmentEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.departmentEdit.setObjectName("departmentEdit")
        self.frame = QtWidgets.QFrame(ClaimPersonDialog)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 611, 80))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(210, 0, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(ClaimPersonDialog)
        self.label_10.setGeometry(QtCore.QRect(21, 250, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lastNameEdit = QtWidgets.QLineEdit(ClaimPersonDialog)
        self.lastNameEdit.setGeometry(QtCore.QRect(300, 190, 271, 41))
        self.lastNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.label_8 = QtWidgets.QLabel(ClaimPersonDialog)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(ClaimPersonDialog)
        self.label_9.setGeometry(QtCore.QRect(21, 160, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.firstNameEdit = QtWidgets.QLineEdit(ClaimPersonDialog)
        self.firstNameEdit.setGeometry(QtCore.QRect(10, 190, 271, 41))
        self.firstNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.label_13 = QtWidgets.QLabel(ClaimPersonDialog)
        self.label_13.setGeometry(QtCore.QRect(11, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.proofImagePreview = QtWidgets.QLabel(ClaimPersonDialog)
        self.proofImagePreview.setGeometry(QtCore.QRect(10, 360, 441, 231))
        self.proofImagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.proofImagePreview.setObjectName("proofImagePreview")
        self.label_12 = QtWidgets.QLabel(ClaimPersonDialog)
        self.label_12.setGeometry(QtCore.QRect(310, 250, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.uploadImageButton = QtWidgets.QPushButton(ClaimPersonDialog)
        self.uploadImageButton.setGeometry(QtCore.QRect(460, 450, 75, 31))
        self.uploadImageButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.uploadImageButton.setObjectName("uploadImageButton")

        self.retranslateUi(ClaimPersonDialog)
        QtCore.QMetaObject.connectSlotsByName(ClaimPersonDialog)

    def retranslateUi(self, ClaimPersonDialog):
        _translate = QtCore.QCoreApplication.translate
        ClaimPersonDialog.setWindowTitle(_translate("ClaimPersonDialog", "Dialog"))
        self.confirmButton.setText(_translate("ClaimPersonDialog", "Confirm"))
        self.phoneNumberEdit.setPlaceholderText(_translate("ClaimPersonDialog", "e.g. 09123456789"))
        self.cancelButton.setText(_translate("ClaimPersonDialog", "Cancel"))
        self.departmentEdit.setPlaceholderText(_translate("ClaimPersonDialog", "e.g. BSCS"))
        self.label.setText(_translate("ClaimPersonDialog", "Claim an Item"))
        self.label_10.setText(_translate("ClaimPersonDialog", "Phone Number"))
        self.lastNameEdit.setPlaceholderText(_translate("ClaimPersonDialog", "Last Name"))
        self.label_8.setText(_translate("ClaimPersonDialog", "Proof ID"))
        self.label_9.setText(_translate("ClaimPersonDialog", "Name"))
        self.firstNameEdit.setPlaceholderText(_translate("ClaimPersonDialog", "First Name"))
        self.label_13.setText(_translate("ClaimPersonDialog", "Personal Details"))
        self.proofImagePreview.setText(_translate("ClaimPersonDialog", "No Image Selected"))
        self.label_12.setText(_translate("ClaimPersonDialog", "Department"))
        self.uploadImageButton.setText(_translate("ClaimPersonDialog", "Upload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClaimPersonDialog = QtWidgets.QDialog()
    ui = Ui_ClaimPersonDialog()
    ui.setupUi(ClaimPersonDialog)
    ClaimPersonDialog.show()
    sys.exit(app.exec_())
