# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 1111, 961))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.layoutWidget_7 = QtWidgets.QWidget(self.homePage)
        self.layoutWidget_7.setGeometry(QtCore.QRect(40, 200, 921, 48))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_26.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 13pt \"Futura\";\n"
"    font-weight: bold; \n"
"}")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.layoutWidget_8 = QtWidgets.QWidget(self.homePage)
        self.layoutWidget_8.setGeometry(QtCore.QRect(40, 260, 981, 291))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame5 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame5.setStyleSheet("")
        self.frame5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.frame_12 = QtWidgets.QFrame(self.frame5)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_36 = QtWidgets.QLabel(self.frame5)
        self.label_36.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.frame5)
        self.frame2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.frame_14 = QtWidgets.QFrame(self.frame2)
        self.frame_14.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_37 = QtWidgets.QLabel(self.frame2)
        self.label_37.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.frame2)
        self.frame3 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.frame_16 = QtWidgets.QFrame(self.frame3)
        self.frame_16.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_38 = QtWidgets.QLabel(self.frame3)
        self.label_38.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.frame3)
        self.frame4 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame4.setObjectName("frame4")
        self.frame_18 = QtWidgets.QFrame(self.frame4)
        self.frame_18.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_39 = QtWidgets.QLabel(self.frame4)
        self.label_39.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.frame4)
        self.frame1 = QtWidgets.QFrame(self.layoutWidget_8)
        self.frame1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.frame_20 = QtWidgets.QFrame(self.frame1)
        self.frame_20.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_40 = QtWidgets.QLabel(self.frame1)
        self.label_40.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.frame1)
        self.reportItem = QtWidgets.QPushButton(self.homePage)
        self.reportItem.setGeometry(QtCore.QRect(870, 30, 151, 51))
        self.reportItem.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 35px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.reportItem.setObjectName("reportItem")
        self.surrenderItem = QtWidgets.QPushButton(self.homePage)
        self.surrenderItem.setGeometry(QtCore.QRect(870, 90, 151, 51))
        self.surrenderItem.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 35px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.surrenderItem.setObjectName("surrenderItem")
        self.textEdit = QtWidgets.QTextEdit(self.homePage)
        self.textEdit.setGeometry(QtCore.QRect(40, 20, 811, 101))
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.homePage)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 130, 821, 61))
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.stackedWidget.addWidget(self.homePage)
        self.managePersonsPage = QtWidgets.QWidget()
        self.managePersonsPage.setObjectName("managePersonsPage")
        self.label_3 = QtWidgets.QLabel(self.managePersonsPage)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.personTable = QtWidgets.QTableWidget(self.managePersonsPage)
        self.personTable.setGeometry(QtCore.QRect(10, 100, 1091, 751))
        self.personTable.setObjectName("personTable")
        self.personTable.setColumnCount(6)
        self.personTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(5, item)
        self.pushButton_7 = QtWidgets.QPushButton(self.managePersonsPage)
        self.pushButton_7.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.pushButton_7.setObjectName("pushButton_7")
        self.personSearchEdit = QtWidgets.QLineEdit(self.managePersonsPage)
        self.personSearchEdit.setGeometry(QtCore.QRect(10, 50, 401, 41))
        self.personSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.personSearchEdit.setObjectName("personSearchEdit")
        self.personSearchButton = QtWidgets.QPushButton(self.managePersonsPage)
        self.personSearchButton.setGeometry(QtCore.QRect(430, 50, 112, 41))
        self.personSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.personSearchButton.setObjectName("personSearchButton")
        self.layoutWidget = QtWidgets.QWidget(self.managePersonsPage)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.personPrev = QtWidgets.QPushButton(self.layoutWidget)
        self.personPrev.setObjectName("personPrev")
        self.horizontalLayout.addWidget(self.personPrev)
        self.personPageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.personPageLabel.setObjectName("personPageLabel")
        self.horizontalLayout.addWidget(self.personPageLabel)
        self.personNext = QtWidgets.QPushButton(self.layoutWidget)
        self.personNext.setObjectName("personNext")
        self.horizontalLayout.addWidget(self.personNext)
        self.stackedWidget.addWidget(self.managePersonsPage)
        self.manageItemsPage = QtWidgets.QWidget()
        self.manageItemsPage.setObjectName("manageItemsPage")
        self.label_7 = QtWidgets.QLabel(self.manageItemsPage)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.itemUpdateButton = QtWidgets.QPushButton(self.manageItemsPage)
        self.itemUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.itemUpdateButton.setObjectName("itemUpdateButton")
        self.matchTable = QtWidgets.QTableWidget(self.manageItemsPage)
        self.matchTable.setGeometry(QtCore.QRect(10, 100, 1091, 751))
        self.matchTable.setObjectName("matchTable")
        self.matchTable.setColumnCount(5)
        self.matchTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.matchTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.matchTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.matchTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.matchTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.matchTable.setHorizontalHeaderItem(4, item)
        self.itemSearchButton = QtWidgets.QPushButton(self.manageItemsPage)
        self.itemSearchButton.setGeometry(QtCore.QRect(430, 50, 112, 41))
        self.itemSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.itemSearchButton.setObjectName("itemSearchButton")
        self.itemSearchEdit = QtWidgets.QLineEdit(self.manageItemsPage)
        self.itemSearchEdit.setGeometry(QtCore.QRect(10, 50, 401, 41))
        self.itemSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.itemSearchEdit.setObjectName("itemSearchEdit")
        self.layoutWidget_5 = QtWidgets.QWidget(self.manageItemsPage)
        self.layoutWidget_5.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.itemPrevButton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.itemPrevButton.setObjectName("itemPrevButton")
        self.horizontalLayout_5.addWidget(self.itemPrevButton)
        self.personPageLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.personPageLabel_2.setObjectName("personPageLabel_2")
        self.horizontalLayout_5.addWidget(self.personPageLabel_2)
        self.itemNextButton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.itemNextButton.setObjectName("itemNextButton")
        self.horizontalLayout_5.addWidget(self.itemNextButton)
        self.stackedWidget.addWidget(self.manageItemsPage)
        self.claimedItems = QtWidgets.QWidget()
        self.claimedItems.setObjectName("claimedItems")
        self.claimSearchEdit = QtWidgets.QLineEdit(self.claimedItems)
        self.claimSearchEdit.setGeometry(QtCore.QRect(10, 50, 401, 41))
        self.claimSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.claimSearchEdit.setObjectName("claimSearchEdit")
        self.claimTable = QtWidgets.QTableWidget(self.claimedItems)
        self.claimTable.setGeometry(QtCore.QRect(10, 100, 1091, 751))
        self.claimTable.setObjectName("claimTable")
        self.claimTable.setColumnCount(4)
        self.claimTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(3, item)
        self.deleteClaimButton = QtWidgets.QPushButton(self.claimedItems)
        self.deleteClaimButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.deleteClaimButton.setObjectName("deleteClaimButton")
        self.claimSearchButton = QtWidgets.QPushButton(self.claimedItems)
        self.claimSearchButton.setGeometry(QtCore.QRect(430, 50, 112, 41))
        self.claimSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.claimSearchButton.setObjectName("claimSearchButton")
        self.layoutWidget_2 = QtWidgets.QWidget(self.claimedItems)
        self.layoutWidget_2.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.claimPrev = QtWidgets.QPushButton(self.layoutWidget_2)
        self.claimPrev.setObjectName("claimPrev")
        self.horizontalLayout_2.addWidget(self.claimPrev)
        self.claimPageLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.claimPageLabel.setObjectName("claimPageLabel")
        self.horizontalLayout_2.addWidget(self.claimPageLabel)
        self.claimNext = QtWidgets.QPushButton(self.layoutWidget_2)
        self.claimNext.setObjectName("claimNext")
        self.horizontalLayout_2.addWidget(self.claimNext)
        self.updateClaimButton = QtWidgets.QPushButton(self.claimedItems)
        self.updateClaimButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.updateClaimButton.setObjectName("updateClaimButton")
        self.label_9 = QtWidgets.QLabel(self.claimedItems)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.claimedItems)
        self.reportedItems = QtWidgets.QWidget()
        self.reportedItems.setObjectName("reportedItems")
        self.reportSearchEdit = QtWidgets.QLineEdit(self.reportedItems)
        self.reportSearchEdit.setGeometry(QtCore.QRect(10, 50, 401, 41))
        self.reportSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.reportSearchEdit.setObjectName("reportSearchEdit")
        self.layoutWidget_3 = QtWidgets.QWidget(self.reportedItems)
        self.layoutWidget_3.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reportPrev = QtWidgets.QPushButton(self.layoutWidget_3)
        self.reportPrev.setObjectName("reportPrev")
        self.horizontalLayout_3.addWidget(self.reportPrev)
        self.reportPageLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.reportPageLabel.setObjectName("reportPageLabel")
        self.horizontalLayout_3.addWidget(self.reportPageLabel)
        self.reportNext = QtWidgets.QPushButton(self.layoutWidget_3)
        self.reportNext.setObjectName("reportNext")
        self.horizontalLayout_3.addWidget(self.reportNext)
        self.reportUpdateButton = QtWidgets.QPushButton(self.reportedItems)
        self.reportUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.reportUpdateButton.setObjectName("reportUpdateButton")
        self.deleteReportButton = QtWidgets.QPushButton(self.reportedItems)
        self.deleteReportButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.deleteReportButton.setObjectName("deleteReportButton")
        self.reportSearchButton = QtWidgets.QPushButton(self.reportedItems)
        self.reportSearchButton.setGeometry(QtCore.QRect(430, 50, 112, 41))
        self.reportSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.reportSearchButton.setObjectName("reportSearchButton")
        self.reportTable = QtWidgets.QTableWidget(self.reportedItems)
        self.reportTable.setGeometry(QtCore.QRect(10, 100, 1091, 751))
        self.reportTable.setObjectName("reportTable")
        self.reportTable.setColumnCount(5)
        self.reportTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(4, item)
        self.label_10 = QtWidgets.QLabel(self.reportedItems)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.reportedItems)
        self.surrenderedItems = QtWidgets.QWidget()
        self.surrenderedItems.setObjectName("surrenderedItems")
        self.surrenderUpdateButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.surrenderUpdateButton.setObjectName("surrenderUpdateButton")
        self.surrenderSearchButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderSearchButton.setGeometry(QtCore.QRect(430, 50, 112, 41))
        self.surrenderSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.surrenderSearchButton.setObjectName("surrenderSearchButton")
        self.surrenederSearchEdit = QtWidgets.QLineEdit(self.surrenderedItems)
        self.surrenederSearchEdit.setGeometry(QtCore.QRect(10, 50, 401, 41))
        self.surrenederSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.surrenederSearchEdit.setObjectName("surrenederSearchEdit")
        self.layoutWidget_4 = QtWidgets.QWidget(self.surrenderedItems)
        self.layoutWidget_4.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.surrenderPrev = QtWidgets.QPushButton(self.layoutWidget_4)
        self.surrenderPrev.setObjectName("surrenderPrev")
        self.horizontalLayout_4.addWidget(self.surrenderPrev)
        self.surrenederPageLabel = QtWidgets.QLabel(self.layoutWidget_4)
        self.surrenederPageLabel.setObjectName("surrenederPageLabel")
        self.horizontalLayout_4.addWidget(self.surrenederPageLabel)
        self.surrenderNext = QtWidgets.QPushButton(self.layoutWidget_4)
        self.surrenderNext.setObjectName("surrenderNext")
        self.horizontalLayout_4.addWidget(self.surrenderNext)
        self.surrenderTable = QtWidgets.QTableWidget(self.surrenderedItems)
        self.surrenderTable.setGeometry(QtCore.QRect(10, 100, 1091, 751))
        self.surrenderTable.setObjectName("surrenderTable")
        self.surrenderTable.setColumnCount(5)
        self.surrenderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(4, item)
        self.surrenderDeleteButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderDeleteButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.surrenderDeleteButton.setObjectName("surrenderDeleteButton")
        self.label_6 = QtWidgets.QLabel(self.surrenderedItems)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.surrenderedItems)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 201, 961))
        self.sidebar.setStyleSheet("background-color: maroon;")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_4.setContentsMargins(10, 30, 10, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.sidebar)
        self.homeButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_3.addWidget(self.homeButton)
        self.managePersonsButton = QtWidgets.QPushButton(self.sidebar)
        self.managePersonsButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.managePersonsButton.setObjectName("managePersonsButton")
        self.verticalLayout_3.addWidget(self.managePersonsButton)
        self.reviewItemsButton = QtWidgets.QPushButton(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reviewItemsButton.sizePolicy().hasHeightForWidth())
        self.reviewItemsButton.setSizePolicy(sizePolicy)
        self.reviewItemsButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.reviewItemsButton.setObjectName("reviewItemsButton")
        self.verticalLayout_3.addWidget(self.reviewItemsButton)
        self.manage_items = QtWidgets.QFrame(self.sidebar)
        self.manage_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manage_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manage_items.setObjectName("manage_items")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.manage_items)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.itemHistoryButton = QtWidgets.QPushButton(self.manage_items)
        self.itemHistoryButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.itemHistoryButton.setCheckable(True)
        self.itemHistoryButton.setObjectName("itemHistoryButton")
        self.verticalLayout_2.addWidget(self.itemHistoryButton)
        self.item_dropdown = QtWidgets.QFrame(self.manage_items)
        self.item_dropdown.setStyleSheet("color: rgb(255, 255, 255);")
        self.item_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.item_dropdown.setObjectName("item_dropdown")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.item_dropdown)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.claimItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.claimItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 5px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.claimItemButton.setCheckable(True)
        self.claimItemButton.setObjectName("claimItemButton")
        self.verticalLayout.addWidget(self.claimItemButton)
        self.reportItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.reportItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 20px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.reportItemButton.setCheckable(True)
        self.reportItemButton.setObjectName("reportItemButton")
        self.verticalLayout.addWidget(self.reportItemButton)
        self.surrenderItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.surrenderItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 45px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.surrenderItemButton.setCheckable(True)
        self.surrenderItemButton.setObjectName("surrenderItemButton")
        self.verticalLayout.addWidget(self.surrenderItemButton)
        self.verticalLayout_2.addWidget(self.item_dropdown)
        self.verticalLayout_3.addWidget(self.manage_items)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 614, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.itemHistoryButton.toggled['bool'].connect(self.item_dropdown.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_26.setText(_translate("MainWindow", "Recent Items"))
        self.label_36.setText(_translate("MainWindow", "Item Description"))
        self.label_37.setText(_translate("MainWindow", "Item Description"))
        self.label_38.setText(_translate("MainWindow", "Item Description"))
        self.label_39.setText(_translate("MainWindow", "Item Description"))
        self.label_40.setText(_translate("MainWindow", "Item Description"))
        self.reportItem.setText(_translate("MainWindow", "Report Item"))
        self.surrenderItem.setText(_translate("MainWindow", "Surrender Item"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:28pt; font-weight:600;\">Welcome to the </span><span style=\" font-family:\'Century Gothic\'; font-size:28pt; font-weight:600; color:#aa0000;\">Lost</span><span style=\" font-family:\'Century Gothic\'; font-size:28pt; font-weight:600;\"> and <br /></span><span style=\" font-family:\'Century Gothic\'; font-size:28pt; font-weight:600; color:#ffca40;\">Found</span><span style=\" font-family:\'Century Gothic\'; font-size:28pt; font-weight:600;\"> System</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:12pt; font-weight:600;\">Let us help you find what you are looking for or return something you found</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Person Management Page"))
        item = self.personTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PersonID"))
        item = self.personTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.personTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.personTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.personTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Department"))
        item = self.personTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ProofID"))
        self.pushButton_7.setText(_translate("MainWindow", "Update"))
        self.personSearchButton.setText(_translate("MainWindow", "Search"))
        self.personPrev.setText(_translate("MainWindow", "Prev"))
        self.personPageLabel.setText(_translate("MainWindow", "Page"))
        self.personNext.setText(_translate("MainWindow", "Next"))
        self.label_7.setText(_translate("MainWindow", "Review Items Page"))
        self.itemUpdateButton.setText(_translate("MainWindow", "Claim"))
        item = self.matchTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.matchTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category"))
        item = self.matchTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.matchTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.matchTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.itemSearchButton.setText(_translate("MainWindow", "Search"))
        self.itemPrevButton.setText(_translate("MainWindow", "Prev"))
        self.personPageLabel_2.setText(_translate("MainWindow", "Page"))
        self.itemNextButton.setText(_translate("MainWindow", "Next"))
        item = self.claimTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.claimTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.claimTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Claimed"))
        item = self.claimTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Claimed By"))
        self.deleteClaimButton.setText(_translate("MainWindow", "Delete"))
        self.claimSearchButton.setText(_translate("MainWindow", "Search"))
        self.claimPrev.setText(_translate("MainWindow", "Prev"))
        self.claimPageLabel.setText(_translate("MainWindow", "Page"))
        self.claimNext.setText(_translate("MainWindow", "Next"))
        self.updateClaimButton.setText(_translate("MainWindow", "Update"))
        self.label_9.setText(_translate("MainWindow", "Claimed Items Page"))
        self.reportPrev.setText(_translate("MainWindow", "Prev"))
        self.reportPageLabel.setText(_translate("MainWindow", "Page"))
        self.reportNext.setText(_translate("MainWindow", "Next"))
        self.reportUpdateButton.setText(_translate("MainWindow", "Update"))
        self.deleteReportButton.setText(_translate("MainWindow", "Delete"))
        self.reportSearchButton.setText(_translate("MainWindow", "Search"))
        item = self.reportTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.reportTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.reportTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Claimed"))
        item = self.reportTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location Lost"))
        item = self.reportTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reported By"))
        self.label_10.setText(_translate("MainWindow", "Reported Items Page"))
        self.surrenderUpdateButton.setText(_translate("MainWindow", "Update"))
        self.surrenderSearchButton.setText(_translate("MainWindow", "Search"))
        self.surrenderPrev.setText(_translate("MainWindow", "Prev"))
        self.surrenederPageLabel.setText(_translate("MainWindow", "Page"))
        self.surrenderNext.setText(_translate("MainWindow", "Next"))
        item = self.surrenderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.surrenderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.surrenderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Found"))
        item = self.surrenderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location Found"))
        item = self.surrenderTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Surrendered By"))
        self.surrenderDeleteButton.setText(_translate("MainWindow", "Claim"))
        self.label_6.setText(_translate("MainWindow", "Surrendered Items Page"))
        self.label.setText(_translate("MainWindow", "     Lost and Found"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.managePersonsButton.setText(_translate("MainWindow", "Manage Persons"))
        self.reviewItemsButton.setText(_translate("MainWindow", "Review Items"))
        self.itemHistoryButton.setText(_translate("MainWindow", "Item History"))
        self.claimItemButton.setText(_translate("MainWindow", "Claimed"))
        self.reportItemButton.setText(_translate("MainWindow", "Reported"))
        self.surrenderItemButton.setText(_translate("MainWindow", "Surrendered"))
