# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 1111, 961))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.layoutWidget_6 = QtWidgets.QWidget(self.homePage)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 0, 587, 90))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_25.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 20pt \"Futura\";\n"
"    font-weight: bold; \n"
"}")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_8.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 10pt \"Century Gothic\";\n"
"    weight: bold;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.layoutWidget_7 = QtWidgets.QWidget(self.homePage)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 90, 921, 39))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_26.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 13pt \"Futura\";\n"
"    font-weight: bold; \n"
"}")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.layoutWidget_8 = QtWidgets.QWidget(self.homePage)
        self.layoutWidget_8.setGeometry(QtCore.QRect(30, 140, 981, 291))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.recentFrame1_2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.recentFrame1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFrame1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFrame1_2.setObjectName("recentFrame1_2")
        self.frame_12 = QtWidgets.QFrame(self.recentFrame1_2)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_36 = QtWidgets.QLabel(self.recentFrame1_2)
        self.label_36.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.recentFrame1_2)
        self.recentFrame2_2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.recentFrame2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFrame2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFrame2_2.setObjectName("recentFrame2_2")
        self.frame_14 = QtWidgets.QFrame(self.recentFrame2_2)
        self.frame_14.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_37 = QtWidgets.QLabel(self.recentFrame2_2)
        self.label_37.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.recentFrame2_2)
        self.recentFrame3_2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.recentFrame3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFrame3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFrame3_2.setObjectName("recentFrame3_2")
        self.frame_16 = QtWidgets.QFrame(self.recentFrame3_2)
        self.frame_16.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_38 = QtWidgets.QLabel(self.recentFrame3_2)
        self.label_38.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.recentFrame3_2)
        self.recentFrame4_2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.recentFrame4_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFrame4_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFrame4_2.setObjectName("recentFrame4_2")
        self.frame_18 = QtWidgets.QFrame(self.recentFrame4_2)
        self.frame_18.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_39 = QtWidgets.QLabel(self.recentFrame4_2)
        self.label_39.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.recentFrame4_2)
        self.recentFram5_2 = QtWidgets.QFrame(self.layoutWidget_8)
        self.recentFram5_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFram5_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFram5_2.setObjectName("recentFram5_2")
        self.frame_20 = QtWidgets.QFrame(self.recentFram5_2)
        self.frame_20.setGeometry(QtCore.QRect(10, 10, 171, 181))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_40 = QtWidgets.QLabel(self.recentFram5_2)
        self.label_40.setGeometry(QtCore.QRect(10, 200, 121, 21))
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.recentFram5_2)
        self.reportItem = QtWidgets.QPushButton(self.homePage)
        self.reportItem.setGeometry(QtCore.QRect(640, 40, 179, 23))
        self.reportItem.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.reportItem.setCheckable(True)
        self.reportItem.setObjectName("reportItem")
        self.surrenderItem = QtWidgets.QPushButton(self.homePage)
        self.surrenderItem.setGeometry(QtCore.QRect(860, 40, 179, 23))
        self.surrenderItem.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.surrenderItem.setCheckable(True)
        self.surrenderItem.setObjectName("surrenderItem")
        self.stackedWidget.addWidget(self.homePage)
        self.managePersonsPage = QtWidgets.QWidget()
        self.managePersonsPage.setObjectName("managePersonsPage")
        self.label_3 = QtWidgets.QLabel(self.managePersonsPage)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.personTable = QtWidgets.QTableWidget(self.managePersonsPage)
        self.personTable.setGeometry(QtCore.QRect(10, 180, 1091, 661))
        self.personTable.setObjectName("personTable")
        self.personTable.setColumnCount(6)
        self.personTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.personTable.setHorizontalHeaderItem(5, item)
        self.pushButton_7 = QtWidgets.QPushButton(self.managePersonsPage)
        self.pushButton_7.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.managePersonsPage)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.pushButton_8.setObjectName("pushButton_8")
        self.personSearchEdit = QtWidgets.QLineEdit(self.managePersonsPage)
        self.personSearchEdit.setGeometry(QtCore.QRect(10, 130, 401, 41))
        self.personSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.personSearchEdit.setObjectName("personSearchEdit")
        self.personSearchButton = QtWidgets.QPushButton(self.managePersonsPage)
        self.personSearchButton.setGeometry(QtCore.QRect(430, 130, 112, 41))
        self.personSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.personSearchButton.setObjectName("personSearchButton")
        self.layoutWidget = QtWidgets.QWidget(self.managePersonsPage)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.personPrev = QtWidgets.QPushButton(self.layoutWidget)
        self.personPrev.setObjectName("personPrev")
        self.horizontalLayout.addWidget(self.personPrev)
        self.personPageLabel = QtWidgets.QLabel(self.layoutWidget)
        self.personPageLabel.setObjectName("personPageLabel")
        self.horizontalLayout.addWidget(self.personPageLabel)
        self.personNext = QtWidgets.QPushButton(self.layoutWidget)
        self.personNext.setObjectName("personNext")
        self.horizontalLayout.addWidget(self.personNext)
        self.stackedWidget.addWidget(self.managePersonsPage)
        self.manageItemsPage = QtWidgets.QWidget()
        self.manageItemsPage.setObjectName("manageItemsPage")
        self.label_7 = QtWidgets.QLabel(self.manageItemsPage)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.itemUpdateButton = QtWidgets.QPushButton(self.manageItemsPage)
        self.itemUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.itemUpdateButton.setObjectName("itemUpdateButton")
        self.itemTable = QtWidgets.QTableWidget(self.manageItemsPage)
        self.itemTable.setGeometry(QtCore.QRect(10, 180, 1091, 661))
        self.itemTable.setObjectName("itemTable")
        self.itemTable.setColumnCount(5)
        self.itemTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.itemTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.itemTable.setHorizontalHeaderItem(4, item)
        self.itemDeleteButton = QtWidgets.QPushButton(self.manageItemsPage)
        self.itemDeleteButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.itemDeleteButton.setObjectName("itemDeleteButton")
        self.itemSearchButton = QtWidgets.QPushButton(self.manageItemsPage)
        self.itemSearchButton.setGeometry(QtCore.QRect(430, 130, 112, 41))
        self.itemSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.itemSearchButton.setObjectName("itemSearchButton")
        self.itemSearchEdit = QtWidgets.QLineEdit(self.manageItemsPage)
        self.itemSearchEdit.setGeometry(QtCore.QRect(10, 130, 401, 41))
        self.itemSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.itemSearchEdit.setObjectName("itemSearchEdit")
        self.layoutWidget_5 = QtWidgets.QWidget(self.manageItemsPage)
        self.layoutWidget_5.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.itemPrevButton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.itemPrevButton.setObjectName("itemPrevButton")
        self.horizontalLayout_5.addWidget(self.itemPrevButton)
        self.personPageLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.personPageLabel_2.setObjectName("personPageLabel_2")
        self.horizontalLayout_5.addWidget(self.personPageLabel_2)
        self.itemNextButton = QtWidgets.QPushButton(self.layoutWidget_5)
        self.itemNextButton.setObjectName("itemNextButton")
        self.horizontalLayout_5.addWidget(self.itemNextButton)
        self.stackedWidget.addWidget(self.manageItemsPage)
        self.reportedItems = QtWidgets.QWidget()
        self.reportedItems.setObjectName("reportedItems")
        self.claimSearchEdit = QtWidgets.QLineEdit(self.reportedItems)
        self.claimSearchEdit.setGeometry(QtCore.QRect(10, 130, 401, 41))
        self.claimSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.claimSearchEdit.setObjectName("claimSearchEdit")
        self.claimTable = QtWidgets.QTableWidget(self.reportedItems)
        self.claimTable.setGeometry(QtCore.QRect(10, 180, 1091, 661))
        self.claimTable.setObjectName("claimTable")
        self.claimTable.setColumnCount(5)
        self.claimTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.claimTable.setHorizontalHeaderItem(4, item)
        self.deleteClaimButton = QtWidgets.QPushButton(self.reportedItems)
        self.deleteClaimButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.deleteClaimButton.setObjectName("deleteClaimButton")
        self.claimSearchButton = QtWidgets.QPushButton(self.reportedItems)
        self.claimSearchButton.setGeometry(QtCore.QRect(430, 130, 112, 41))
        self.claimSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.claimSearchButton.setObjectName("claimSearchButton")
        self.layoutWidget_2 = QtWidgets.QWidget(self.reportedItems)
        self.layoutWidget_2.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.claimPrev = QtWidgets.QPushButton(self.layoutWidget_2)
        self.claimPrev.setObjectName("claimPrev")
        self.horizontalLayout_2.addWidget(self.claimPrev)
        self.claimPageLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.claimPageLabel.setObjectName("claimPageLabel")
        self.horizontalLayout_2.addWidget(self.claimPageLabel)
        self.claimNext = QtWidgets.QPushButton(self.layoutWidget_2)
        self.claimNext.setObjectName("claimNext")
        self.horizontalLayout_2.addWidget(self.claimNext)
        self.updateClaimButton = QtWidgets.QPushButton(self.reportedItems)
        self.updateClaimButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.updateClaimButton.setObjectName("updateClaimButton")
        self.label_9 = QtWidgets.QLabel(self.reportedItems)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.reportedItems)
        self.claimedItems = QtWidgets.QWidget()
        self.claimedItems.setObjectName("claimedItems")
        self.reportSearchEdit = QtWidgets.QLineEdit(self.claimedItems)
        self.reportSearchEdit.setGeometry(QtCore.QRect(10, 130, 401, 41))
        self.reportSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.reportSearchEdit.setObjectName("reportSearchEdit")
        self.layoutWidget_3 = QtWidgets.QWidget(self.claimedItems)
        self.layoutWidget_3.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reportPrev = QtWidgets.QPushButton(self.layoutWidget_3)
        self.reportPrev.setObjectName("reportPrev")
        self.horizontalLayout_3.addWidget(self.reportPrev)
        self.reportPageLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.reportPageLabel.setObjectName("reportPageLabel")
        self.horizontalLayout_3.addWidget(self.reportPageLabel)
        self.reportNext = QtWidgets.QPushButton(self.layoutWidget_3)
        self.reportNext.setObjectName("reportNext")
        self.horizontalLayout_3.addWidget(self.reportNext)
        self.reportUpdateButton = QtWidgets.QPushButton(self.claimedItems)
        self.reportUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.reportUpdateButton.setObjectName("reportUpdateButton")
        self.deleteClaimButton_2 = QtWidgets.QPushButton(self.claimedItems)
        self.deleteClaimButton_2.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.deleteClaimButton_2.setObjectName("deleteClaimButton_2")
        self.reportSearchButton = QtWidgets.QPushButton(self.claimedItems)
        self.reportSearchButton.setGeometry(QtCore.QRect(430, 130, 112, 41))
        self.reportSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.reportSearchButton.setObjectName("reportSearchButton")
        self.reportTable = QtWidgets.QTableWidget(self.claimedItems)
        self.reportTable.setGeometry(QtCore.QRect(10, 180, 1091, 661))
        self.reportTable.setObjectName("reportTable")
        self.reportTable.setColumnCount(4)
        self.reportTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.reportTable.setHorizontalHeaderItem(3, item)
        self.label_10 = QtWidgets.QLabel(self.claimedItems)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.claimedItems)
        self.surrenderedItems = QtWidgets.QWidget()
        self.surrenderedItems.setObjectName("surrenderedItems")
        self.surrenderUpdateButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderUpdateButton.setGeometry(QtCore.QRect(990, 860, 112, 34))
        self.surrenderUpdateButton.setObjectName("surrenderUpdateButton")
        self.surrenderSearchButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderSearchButton.setGeometry(QtCore.QRect(430, 130, 112, 41))
        self.surrenderSearchButton.setStyleSheet("QPushButton {\n"
"                background-color: maroon;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 20px;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #a00000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #700000;\n"
"            }")
        self.surrenderSearchButton.setObjectName("surrenderSearchButton")
        self.surrenederSearchEdit = QtWidgets.QLineEdit(self.surrenderedItems)
        self.surrenederSearchEdit.setGeometry(QtCore.QRect(10, 130, 401, 41))
        self.surrenederSearchEdit.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #ccc;\n"
"                border-radius: 15px;\n"
"                padding: 6px 12px;\n"
"                background-color: #f9f9f9;\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border: 1px solid #0078d7;\n"
"                background-color: #ffffff;\n"
"            }")
        self.surrenederSearchEdit.setObjectName("surrenederSearchEdit")
        self.layoutWidget_4 = QtWidgets.QWidget(self.surrenderedItems)
        self.layoutWidget_4.setGeometry(QtCore.QRect(390, 850, 341, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.surrenderPrev = QtWidgets.QPushButton(self.layoutWidget_4)
        self.surrenderPrev.setObjectName("surrenderPrev")
        self.horizontalLayout_4.addWidget(self.surrenderPrev)
        self.surrenederPageLabel = QtWidgets.QLabel(self.layoutWidget_4)
        self.surrenederPageLabel.setObjectName("surrenederPageLabel")
        self.horizontalLayout_4.addWidget(self.surrenederPageLabel)
        self.surrenderNext = QtWidgets.QPushButton(self.layoutWidget_4)
        self.surrenderNext.setObjectName("surrenderNext")
        self.horizontalLayout_4.addWidget(self.surrenderNext)
        self.surrenderTable = QtWidgets.QTableWidget(self.surrenderedItems)
        self.surrenderTable.setGeometry(QtCore.QRect(10, 180, 1091, 661))
        self.surrenderTable.setObjectName("surrenderTable")
        self.surrenderTable.setColumnCount(5)
        self.surrenderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.surrenderTable.setHorizontalHeaderItem(4, item)
        self.surrenderDeleteButton = QtWidgets.QPushButton(self.surrenderedItems)
        self.surrenderDeleteButton.setGeometry(QtCore.QRect(10, 860, 112, 34))
        self.surrenderDeleteButton.setObjectName("surrenderDeleteButton")
        self.label_6 = QtWidgets.QLabel(self.surrenderedItems)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.surrenderedItems)
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 201, 961))
        self.sidebar.setStyleSheet("background-color: maroon;")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_4.setContentsMargins(10, 30, 10, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.sidebar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.sidebar)
        self.homeButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_3.addWidget(self.homeButton)
        self.managePersonsButton = QtWidgets.QPushButton(self.sidebar)
        self.managePersonsButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.managePersonsButton.setObjectName("managePersonsButton")
        self.verticalLayout_3.addWidget(self.managePersonsButton)
        self.manageItemsButton = QtWidgets.QPushButton(self.sidebar)
        self.manageItemsButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.manageItemsButton.setObjectName("manageItemsButton")
        self.verticalLayout_3.addWidget(self.manageItemsButton)
        self.manage_items = QtWidgets.QFrame(self.sidebar)
        self.manage_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manage_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manage_items.setObjectName("manage_items")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.manage_items)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.itemHistoryButton = QtWidgets.QPushButton(self.manage_items)
        self.itemHistoryButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.itemHistoryButton.setCheckable(True)
        self.itemHistoryButton.setObjectName("itemHistoryButton")
        self.verticalLayout_2.addWidget(self.itemHistoryButton)
        self.item_dropdown = QtWidgets.QFrame(self.manage_items)
        self.item_dropdown.setStyleSheet("color: rgb(255, 255, 255);")
        self.item_dropdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.item_dropdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.item_dropdown.setObjectName("item_dropdown")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.item_dropdown)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.claimItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.claimItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 5px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.claimItemButton.setCheckable(True)
        self.claimItemButton.setObjectName("claimItemButton")
        self.verticalLayout.addWidget(self.claimItemButton)
        self.reportItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.reportItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 20px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.reportItemButton.setCheckable(True)
        self.reportItemButton.setObjectName("reportItemButton")
        self.verticalLayout.addWidget(self.reportItemButton)
        self.surrenderItemButton = QtWidgets.QPushButton(self.item_dropdown)
        self.surrenderItemButton.setStyleSheet("QPushButton {\n"
"    padding-left: 45px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: yellow; \n"
"}")
        self.surrenderItemButton.setCheckable(True)
        self.surrenderItemButton.setObjectName("surrenderItemButton")
        self.verticalLayout.addWidget(self.surrenderItemButton)
        self.verticalLayout_2.addWidget(self.item_dropdown)
        self.verticalLayout_3.addWidget(self.manage_items)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 614, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.itemHistoryButton.toggled['bool'].connect(self.item_dropdown.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_25.setText(_translate("MainWindow", "Welcome to the Lost and Found System!"))
        self.label_8.setText(_translate("MainWindow", "Let us help you find what you\'re looking for or return something you found."))
        self.label_26.setText(_translate("MainWindow", "Recent Items"))
        self.label_36.setText(_translate("MainWindow", "Item Description"))
        self.label_37.setText(_translate("MainWindow", "Item Description"))
        self.label_38.setText(_translate("MainWindow", "Item Description"))
        self.label_39.setText(_translate("MainWindow", "Item Description"))
        self.label_40.setText(_translate("MainWindow", "Item Description"))
        self.reportItem.setText(_translate("MainWindow", "Report Item"))
        self.surrenderItem.setText(_translate("MainWindow", "Surrender Item"))
        self.label_3.setText(_translate("MainWindow", "Person Management Page"))
        item = self.personTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PersonID"))
        item = self.personTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.personTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.personTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.personTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Department"))
        item = self.personTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ProofID"))
        self.pushButton_7.setText(_translate("MainWindow", "Update"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete"))
        self.personSearchButton.setText(_translate("MainWindow", "Search"))
        self.personPrev.setText(_translate("MainWindow", "Prev"))
        self.personPageLabel.setText(_translate("MainWindow", "Page"))
        self.personNext.setText(_translate("MainWindow", "Next"))
        self.label_7.setText(_translate("MainWindow", "Manage Items Page"))
        self.itemUpdateButton.setText(_translate("MainWindow", "Update"))
        item = self.itemTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.itemTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category"))
        item = self.itemTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.itemTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.itemTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.itemDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.itemSearchButton.setText(_translate("MainWindow", "Search"))
        self.itemPrevButton.setText(_translate("MainWindow", "Prev"))
        self.personPageLabel_2.setText(_translate("MainWindow", "Page"))
        self.itemNextButton.setText(_translate("MainWindow", "Next"))
        item = self.claimTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.claimTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.claimTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Lost"))
        item = self.claimTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location Lost"))
        item = self.claimTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reported By"))
        self.deleteClaimButton.setText(_translate("MainWindow", "Delete"))
        self.claimSearchButton.setText(_translate("MainWindow", "Search"))
        self.claimPrev.setText(_translate("MainWindow", "Prev"))
        self.claimPageLabel.setText(_translate("MainWindow", "Page"))
        self.claimNext.setText(_translate("MainWindow", "Next"))
        self.updateClaimButton.setText(_translate("MainWindow", "Update"))
        self.label_9.setText(_translate("MainWindow", "Reported Items Page"))
        self.reportPrev.setText(_translate("MainWindow", "Prev"))
        self.reportPageLabel.setText(_translate("MainWindow", "Page"))
        self.reportNext.setText(_translate("MainWindow", "Next"))
        self.reportUpdateButton.setText(_translate("MainWindow", "Update"))
        self.deleteClaimButton_2.setText(_translate("MainWindow", "Delete"))
        self.reportSearchButton.setText(_translate("MainWindow", "Search"))
        item = self.reportTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.reportTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.reportTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Claimed"))
        item = self.reportTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Claimed By"))
        self.label_10.setText(_translate("MainWindow", "Claimed Items Page"))
        self.surrenderUpdateButton.setText(_translate("MainWindow", "Update"))
        self.surrenderSearchButton.setText(_translate("MainWindow", "Search"))
        self.surrenderPrev.setText(_translate("MainWindow", "Prev"))
        self.surrenederPageLabel.setText(_translate("MainWindow", "Page"))
        self.surrenderNext.setText(_translate("MainWindow", "Next"))
        item = self.surrenderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.surrenderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.surrenderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Found"))
        item = self.surrenderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location Found"))
        item = self.surrenderTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Reported By"))
        self.surrenderDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.label_6.setText(_translate("MainWindow", "Surrendered Items Page"))
        self.label.setText(_translate("MainWindow", "     Lost and Found"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.managePersonsButton.setText(_translate("MainWindow", "MANAGE PERSONS"))
        self.manageItemsButton.setText(_translate("MainWindow", "MANAGE ITEMS"))
        self.itemHistoryButton.setText(_translate("MainWindow", "ITEM HISTORY"))
        self.claimItemButton.setText(_translate("MainWindow", "Claimed"))
        self.reportItemButton.setText(_translate("MainWindow", "Reported"))
        self.surrenderItemButton.setText(_translate("MainWindow", "Surrendered"))
