# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow - untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.iconOnly = QtWidgets.QWidget(self.centralwidget)
        self.iconOnly.setStyleSheet("background-color: rgb(247, 216, 83);")
        self.iconOnly.setObjectName("iconOnly")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.iconOnly)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.iconOnly)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/seal-02.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeIcon = QtWidgets.QPushButton(self.iconOnly)
        self.homeIcon.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.homeIcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeIcon.setIcon(icon)
        self.homeIcon.setIconSize(QtCore.QSize(20, 20))
        self.homeIcon.setCheckable(True)
        self.homeIcon.setAutoExclusive(True)
        self.homeIcon.setObjectName("homeIcon")
        self.verticalLayout.addWidget(self.homeIcon)
        self.browseIcon_2 = QtWidgets.QPushButton(self.iconOnly)
        self.browseIcon_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.browseIcon_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/compass.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseIcon_2.setIcon(icon1)
        self.browseIcon_2.setIconSize(QtCore.QSize(20, 20))
        self.browseIcon_2.setCheckable(True)
        self.browseIcon_2.setAutoExclusive(True)
        self.browseIcon_2.setObjectName("browseIcon_2")
        self.verticalLayout.addWidget(self.browseIcon_2)
        self.reportIcon_2 = QtWidgets.QPushButton(self.iconOnly)
        self.reportIcon_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.reportIcon_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/clipboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportIcon_2.setIcon(icon2)
        self.reportIcon_2.setIconSize(QtCore.QSize(20, 20))
        self.reportIcon_2.setCheckable(True)
        self.reportIcon_2.setAutoExclusive(True)
        self.reportIcon_2.setObjectName("reportIcon_2")
        self.verticalLayout.addWidget(self.reportIcon_2)
        self.matchIcon = QtWidgets.QPushButton(self.iconOnly)
        self.matchIcon.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.matchIcon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.matchIcon.setIcon(icon3)
        self.matchIcon.setIconSize(QtCore.QSize(20, 20))
        self.matchIcon.setCheckable(True)
        self.matchIcon.setAutoExclusive(True)
        self.matchIcon.setObjectName("matchIcon")
        self.verticalLayout.addWidget(self.matchIcon)
        self.reportIcon = QtWidgets.QPushButton(self.iconOnly)
        self.reportIcon.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.reportIcon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/inbox.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportIcon.setIcon(icon4)
        self.reportIcon.setIconSize(QtCore.QSize(20, 20))
        self.reportIcon.setCheckable(True)
        self.reportIcon.setAutoExclusive(True)
        self.reportIcon.setObjectName("reportIcon")
        self.verticalLayout.addWidget(self.reportIcon)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 528, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingsIcon = QtWidgets.QPushButton(self.iconOnly)
        self.settingsIcon.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.settingsIcon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsIcon.setIcon(icon5)
        self.settingsIcon.setIconSize(QtCore.QSize(20, 20))
        self.settingsIcon.setObjectName("settingsIcon")
        self.verticalLayout_2.addWidget(self.settingsIcon)
        self.logoutIcon = QtWidgets.QPushButton(self.iconOnly)
        self.logoutIcon.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.logoutIcon.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutIcon.setIcon(icon6)
        self.logoutIcon.setIconSize(QtCore.QSize(20, 20))
        self.logoutIcon.setObjectName("logoutIcon")
        self.verticalLayout_2.addWidget(self.logoutIcon)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.iconOnly, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgb(247, 216, 83);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/seal-02.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 15, 5, -1)
        self.verticalLayout_3.setSpacing(14)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(20, 20))
        self.homeButton.setCheckable(True)
        self.homeButton.setAutoExclusive(True)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_3.addWidget(self.homeButton)
        self.browseButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.browseButton.setFont(font)
        self.browseButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.browseButton.setIcon(icon1)
        self.browseButton.setIconSize(QtCore.QSize(20, 20))
        self.browseButton.setCheckable(True)
        self.browseButton.setAutoExclusive(True)
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout_3.addWidget(self.browseButton)
        self.reportButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.reportButton.setFont(font)
        self.reportButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.reportButton.setIcon(icon2)
        self.reportButton.setIconSize(QtCore.QSize(20, 20))
        self.reportButton.setCheckable(True)
        self.reportButton.setAutoExclusive(True)
        self.reportButton.setObjectName("reportButton")
        self.verticalLayout_3.addWidget(self.reportButton)
        self.matchButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.matchButton.setFont(font)
        self.matchButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.matchButton.setIcon(icon3)
        self.matchButton.setIconSize(QtCore.QSize(20, 20))
        self.matchButton.setCheckable(True)
        self.matchButton.setAutoExclusive(True)
        self.matchButton.setObjectName("matchButton")
        self.verticalLayout_3.addWidget(self.matchButton)
        self.reportButton_2 = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.reportButton_2.setFont(font)
        self.reportButton_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.reportButton_2.setIcon(icon4)
        self.reportButton_2.setIconSize(QtCore.QSize(20, 20))
        self.reportButton_2.setCheckable(True)
        self.reportButton_2.setAutoExclusive(True)
        self.reportButton_2.setObjectName("reportButton_2")
        self.verticalLayout_3.addWidget(self.reportButton_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 528, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settingsButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.settingsButton.setFont(font)
        self.settingsButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.settingsButton.setIcon(icon5)
        self.settingsButton.setIconSize(QtCore.QSize(20, 20))
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_4.addWidget(self.settingsButton)
        self.logoutButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.logoutButton.setIcon(icon6)
        self.logoutButton.setIconSize(QtCore.QSize(20, 20))
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout_4.addWidget(self.logoutButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setStyleSheet("background-color: rgb(149, 26, 31);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon7)
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(279, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon8)
        self.pushButton_17.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.verticalLayout_7.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_25 = QtWidgets.QLabel(self.page)
        self.label_25.setGeometry(QtCore.QRect(0, 40, 581, 51))
        self.label_25.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 20pt \"Futura\";\n"
"    font-weight: bold; \n"
"}")
        self.label_25.setObjectName("label_25")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 531, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 10pt \"Century Gothic\";\n"
"    weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.outisideFrame = QtWidgets.QFrame(self.page)
        self.outisideFrame.setGeometry(QtCore.QRect(20, 120, 861, 371))
        self.outisideFrame.setStyleSheet("")
        self.outisideFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outisideFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outisideFrame.setObjectName("outisideFrame")
        self.label_26 = QtWidgets.QLabel(self.outisideFrame)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 151, 41))
        self.label_26.setStyleSheet("QLabel {\n"
"    padding: 8px 12px;\n"
"    color: #1E1E1E;\n"
"    font: 13pt \"Futura\";\n"
"    font-weight: bold; \n"
"}")
        self.label_26.setObjectName("label_26")
        self.layoutWidget = QtWidgets.QWidget(self.outisideFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 821, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 161, 181))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(10, 200, 121, 91))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 161, 181))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(10, 200, 121, 91))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 161, 181))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 200, 121, 91))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 161, 181))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setGeometry(QtCore.QRect(10, 200, 121, 91))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 891, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lostItems = QtWidgets.QTableWidget(self.tab)
        self.lostItems.setGeometry(QtCore.QRect(10, 60, 861, 681))
        self.lostItems.setObjectName("lostItems")
        self.lostItems.setColumnCount(7)
        self.lostItems.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems.setHorizontalHeaderItem(6, item)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 10, 801, 31))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(780, 20, 16, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/search.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lostItems_2 = QtWidgets.QTableWidget(self.tab_2)
        self.lostItems_2.setGeometry(QtCore.QRect(10, 60, 861, 681))
        self.lostItems_2.setObjectName("lostItems_2")
        self.lostItems_2.setColumnCount(7)
        self.lostItems_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.lostItems_2.setHorizontalHeaderItem(6, item)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 10, 801, 31))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(780, 20, 16, 16))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/icons/icons/search.svg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 150, 801, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(300, 250, 131, 16))
        self.label_14.setObjectName("label_14")
        self.dateEdit = QtWidgets.QDateEdit(self.page_3)
        self.dateEdit.setGeometry(QtCore.QRect(40, 320, 110, 22))
        self.dateEdit.setStyleSheet("")
        self.dateEdit.setObjectName("dateEdit")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(40, 130, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(40, 190, 131, 16))
        self.label_12.setObjectName("label_12")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(40, 300, 131, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 270, 101, 20))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(340, 30, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 320, 161, 20))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 210, 801, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setGeometry(QtCore.QRect(40, 250, 131, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 270, 101, 20))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(300, 300, 131, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 380, 801, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(40, 360, 131, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(50, 430, 131, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(50, 550, 101, 16))
        self.label_19.setObjectName("label_19")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(50, 600, 251, 31))
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_20 = QtWidgets.QLabel(self.page_3)
        self.label_20.setGeometry(QtCore.QRect(50, 580, 61, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(320, 580, 61, 16))
        self.label_21.setObjectName("label_21")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(310, 600, 191, 31))
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(50, 640, 191, 31))
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 640, 191, 31))
        self.lineEdit_12.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(270, 70, 61, 31))
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(self.page_3)
        self.label_22.setGeometry(QtCore.QRect(490, 70, 61, 31))
        self.label_22.setObjectName("label_22")
        self.frame = QtWidgets.QFrame(self.page_3)
        self.frame.setGeometry(QtCore.QRect(50, 460, 791, 80))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 2px solid #D9D9D9;\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame)
        self.pushButton_21.setGeometry(QtCore.QRect(370, 10, 50, 30))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.pushButton_21.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-down-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon9)
        self.pushButton_21.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setAutoExclusive(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(320, 50, 151, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_22 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_22.setGeometry(QtCore.QRect(340, 720, 203, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.pushButton_22.setIcon(icon6)
        self.pushButton_22.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_23.setGeometry(QtCore.QRect(210, 70, 50, 30))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.pushButton_23.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/check-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon10)
        self.pushButton_23.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setAutoExclusive(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_24.setGeometry(QtCore.QRect(430, 70, 50, 30))
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2C3E50;    /* thinner border */\n"
"    border-radius: 10px;           /* small rounding */\n"
"    padding: 4px 8px;             /* top/bottom, left/right */\n"
"    background-color: #951ab;\n"
"    color: black;\n"
"    font-size: 12px;              /* smaller text */\n"
"}\n"
"")
        self.pushButton_24.setText("")
        self.pushButton_24.setIcon(icon10)
        self.pushButton_24.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setAutoExclusive(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setGeometry(QtCore.QRect(390, 390, 47, 13))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setGeometry(QtCore.QRect(390, 380, 47, 13))
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_9 = QtWidgets.QLabel(self.page_6)
        self.label_9.setGeometry(QtCore.QRect(440, 400, 47, 13))
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_6)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_15.toggled['bool'].connect(self.iconOnly.setVisible) # type: ignore
        self.pushButton_15.toggled['bool'].connect(self.widget_2.setHidden) # type: ignore
        self.homeIcon.toggled['bool'].connect(self.homeButton.setChecked) # type: ignore
        self.browseIcon_2.toggled['bool'].connect(self.browseButton.setChecked) # type: ignore
        self.reportIcon_2.toggled['bool'].connect(self.reportButton.setChecked) # type: ignore
        self.matchIcon.toggled['bool'].connect(self.matchButton.setChecked) # type: ignore
        self.reportIcon.toggled['bool'].connect(self.reportButton_2.setChecked) # type: ignore
        self.settingsIcon.toggled['bool'].connect(self.settingsButton.setChecked) # type: ignore
        self.logoutIcon.toggled['bool'].connect(self.logoutButton.setChecked) # type: ignore
        self.homeButton.toggled['bool'].connect(self.homeIcon.setChecked) # type: ignore
        self.browseButton.toggled['bool'].connect(self.browseIcon_2.setChecked) # type: ignore
        self.reportButton.toggled['bool'].connect(self.reportIcon_2.setChecked) # type: ignore
        self.matchButton.toggled['bool'].connect(self.matchIcon.setChecked) # type: ignore
        self.reportButton_2.toggled['bool'].connect(self.reportIcon.setChecked) # type: ignore
        self.settingsButton.toggled['bool'].connect(self.settingsIcon.setChecked) # type: ignore
        self.logoutButton.toggled['bool'].connect(self.logoutIcon.setChecked) # type: ignore

        self.homeIcon.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.homeButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.browseIcon_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.browseButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.reportIcon_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.reportButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.matchIcon.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.matchButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.reportIcon.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))
        self.reportButton_2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(4))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Lost and Found"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.browseButton.setText(_translate("MainWindow", "Browse Items"))
        self.reportButton.setText(_translate("MainWindow", "Report Item"))
        self.matchButton.setText(_translate("MainWindow", "Match Item"))
        self.reportButton_2.setText(_translate("MainWindow", "My Reports"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.logoutButton.setText(_translate("MainWindow", "Log Out"))
        self.label_25.setText(_translate("MainWindow", "Welcome to the Lost and Found System!"))
        self.label_4.setText(_translate("MainWindow", "Let us help you find what you\'re looking for or return something you found."))
        self.label_26.setText(_translate("MainWindow", "Recent Items"))
        self.label_27.setText(_translate("MainWindow", "Item Description"))
        self.label_28.setText(_translate("MainWindow", "Item Description"))
        self.label_29.setText(_translate("MainWindow", "Item Description"))
        self.label_30.setText(_translate("MainWindow", "Item Description"))
        item = self.lostItems.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.lostItems.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Brand/Model"))
        item = self.lostItems.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.lostItems.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        item = self.lostItems.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.lostItems.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Location"))
        item = self.lostItems.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Discoverer"))
        self.lineEdit_8.setText(_translate("MainWindow", "Search Item.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lost Items"))
        item = self.lostItems_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.lostItems_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Brand/Model"))
        item = self.lostItems_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.lostItems_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        item = self.lostItems_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.lostItems_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Location"))
        item = self.lostItems_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Discoverer"))
        self.lineEdit_13.setText(_translate("MainWindow", "Search Item.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Found Items"))
        self.label_14.setText(_translate("MainWindow", "Size (if applicable)"))
        self.label_10.setText(_translate("MainWindow", "Item Details"))
        self.label_12.setText(_translate("MainWindow", "Brand/Model (if applicable)"))
        self.label_15.setText(_translate("MainWindow", "Date Lost"))
        self.label_6.setText(_translate("MainWindow", "Lost and Found Report Form"))
        self.label_13.setText(_translate("MainWindow", "Color"))
        self.label_16.setText(_translate("MainWindow", "Location"))
        self.label_17.setText(_translate("MainWindow", "Description"))
        self.label_18.setText(_translate("MainWindow", "Photos"))
        self.label_19.setText(_translate("MainWindow", "Contact Information:"))
        self.label_20.setText(_translate("MainWindow", "First Name:"))
        self.label_21.setText(_translate("MainWindow", "Last Name:"))
        self.lineEdit_11.setText(_translate("MainWindow", "Email"))
        self.lineEdit_12.setText(_translate("MainWindow", "Phone Number"))
        self.label_11.setText(_translate("MainWindow", "Lost Item"))
        self.label_22.setText(_translate("MainWindow", "Found Item"))
        self.label_23.setText(_translate("MainWindow", "Drag Photos here, or Browse"))
        self.pushButton_22.setText(_translate("MainWindow", "Submit"))
        self.label_7.setText(_translate("MainWindow", "Match"))
        self.label_8.setText(_translate("MainWindow", "Reports"))
        self.label_9.setText(_translate("MainWindow", "Settings"))
import resources_rc
