# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportItemDialog(object):
    def setupUi(self, ReportItemDialog):
        ReportItemDialog.setObjectName("ReportItemDialog")
        ReportItemDialog.resize(602, 682)
        ReportItemDialog.setMinimumSize(QtCore.QSize(602, 682))
        ReportItemDialog.setMaximumSize(QtCore.QSize(602, 682))
        self.stackedWidget = QtWidgets.QStackedWidget(ReportItemDialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 601, 681))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.itemPage = QtWidgets.QWidget()
        self.itemPage.setObjectName("itemPage")
        self.label_2 = QtWidgets.QLabel(self.itemPage)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.itemNameEdit = QtWidgets.QLineEdit(self.itemPage)
        self.itemNameEdit.setGeometry(QtCore.QRect(20, 180, 561, 41))
        self.itemNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.itemNameEdit.setObjectName("itemNameEdit")
        self.label_3 = QtWidgets.QLabel(self.itemPage)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.categoryEdit = QtWidgets.QLineEdit(self.itemPage)
        self.categoryEdit.setGeometry(QtCore.QRect(20, 280, 561, 41))
        self.categoryEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.categoryEdit.setObjectName("categoryEdit")
        self.label_4 = QtWidgets.QLabel(self.itemPage)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dateLostEdit = QtWidgets.QLineEdit(self.itemPage)
        self.dateLostEdit.setGeometry(QtCore.QRect(20, 370, 271, 41))
        self.dateLostEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.dateLostEdit.setObjectName("dateLostEdit")
        self.locationLostEdit = QtWidgets.QLineEdit(self.itemPage)
        self.locationLostEdit.setGeometry(QtCore.QRect(310, 370, 271, 41))
        self.locationLostEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.locationLostEdit.setObjectName("locationLostEdit")
        self.label_5 = QtWidgets.QLabel(self.itemPage)
        self.label_5.setGeometry(QtCore.QRect(30, 340, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.itemPage)
        self.label_6.setGeometry(QtCore.QRect(320, 340, 211, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.descriptionEdit = QtWidgets.QLineEdit(self.itemPage)
        self.descriptionEdit.setGeometry(QtCore.QRect(20, 460, 561, 120))
        self.descriptionEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.label_7 = QtWidgets.QLabel(self.itemPage)
        self.label_7.setGeometry(QtCore.QRect(30, 430, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nextButton = QtWidgets.QPushButton(self.itemPage)
        self.nextButton.setGeometry(QtCore.QRect(369, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.nextButton.setObjectName("nextButton")
        self.cancelButton = QtWidgets.QPushButton(self.itemPage)
        self.cancelButton.setGeometry(QtCore.QRect(20, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton.setObjectName("cancelButton")
        self.frame_2 = QtWidgets.QFrame(self.itemPage)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 611, 80))
        self.frame_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(220, 0, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.itemPage)
        self.personPage = QtWidgets.QWidget()
        self.personPage.setObjectName("personPage")
        self.label_8 = QtWidgets.QLabel(self.personPage)
        self.label_8.setGeometry(QtCore.QRect(30, 340, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.phoneNumberEdit = QtWidgets.QLineEdit(self.personPage)
        self.phoneNumberEdit.setGeometry(QtCore.QRect(30, 270, 271, 41))
        self.phoneNumberEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.phoneNumberEdit.setObjectName("phoneNumberEdit")
        self.cancelButton_2 = QtWidgets.QPushButton(self.personPage)
        self.cancelButton_2.setGeometry(QtCore.QRect(21, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton_2.setFont(font)
        self.cancelButton_2.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton_2.setObjectName("cancelButton_2")
        self.label_9 = QtWidgets.QLabel(self.personPage)
        self.label_9.setGeometry(QtCore.QRect(30, 150, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.personPage)
        self.label_10.setGeometry(QtCore.QRect(30, 240, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.firstNameEdit = QtWidgets.QLineEdit(self.personPage)
        self.firstNameEdit.setGeometry(QtCore.QRect(30, 180, 271, 41))
        self.firstNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.confirmButton = QtWidgets.QPushButton(self.personPage)
        self.confirmButton.setGeometry(QtCore.QRect(370, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.confirmButton.setObjectName("confirmButton")
        self.departmentEdit = QtWidgets.QLineEdit(self.personPage)
        self.departmentEdit.setGeometry(QtCore.QRect(310, 270, 271, 41))
        self.departmentEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.departmentEdit.setObjectName("departmentEdit")
        self.label_13 = QtWidgets.QLabel(self.personPage)
        self.label_13.setGeometry(QtCore.QRect(21, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lastNameEdit = QtWidgets.QLineEdit(self.personPage)
        self.lastNameEdit.setGeometry(QtCore.QRect(310, 180, 271, 41))
        self.lastNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.frame = QtWidgets.QFrame(self.personPage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 611, 80))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 10, 60, 60))
        self.backButton.setStyleSheet("QPushButton {\n"
"        background-color: white;\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.backButton.setObjectName("backButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 0, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(self.personPage)
        self.label_12.setGeometry(QtCore.QRect(310, 240, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.labelImagePreview = QtWidgets.QLabel(self.personPage)
        self.labelImagePreview.setGeometry(QtCore.QRect(110, 370, 291, 201))
        self.labelImagePreview.setObjectName("labelImagePreview")
        self.uploadImageButton = QtWidgets.QPushButton(self.personPage)
        self.uploadImageButton.setGeometry(QtCore.QRect(450, 450, 75, 31))
        self.uploadImageButton.setObjectName("uploadImageButton")
        self.stackedWidget.addWidget(self.personPage)

        self.retranslateUi(ReportItemDialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ReportItemDialog)

    def retranslateUi(self, ReportItemDialog):
        _translate = QtCore.QCoreApplication.translate
        ReportItemDialog.setWindowTitle(_translate("ReportItemDialog", "Dialog"))
        self.label_2.setText(_translate("ReportItemDialog", "Item Details"))
        self.label_3.setText(_translate("ReportItemDialog", "Name"))
        self.label_4.setText(_translate("ReportItemDialog", "Category"))
        self.label_5.setText(_translate("ReportItemDialog", "Date Lost"))
        self.label_6.setText(_translate("ReportItemDialog", "Location Lost"))
        self.label_7.setText(_translate("ReportItemDialog", "Description"))
        self.nextButton.setText(_translate("ReportItemDialog", "Next"))
        self.cancelButton.setText(_translate("ReportItemDialog", "Cancel"))
        self.label_11.setText(_translate("ReportItemDialog", "Report an Item"))
        self.label_8.setText(_translate("ReportItemDialog", "Proof ID"))
        self.phoneNumberEdit.setPlaceholderText(_translate("ReportItemDialog", "e.g. 09123456789"))
        self.cancelButton_2.setText(_translate("ReportItemDialog", "Cancel"))
        self.label_9.setText(_translate("ReportItemDialog", "Name"))
        self.label_10.setText(_translate("ReportItemDialog", "Phone Number"))
        self.firstNameEdit.setPlaceholderText(_translate("ReportItemDialog", "First Name"))
        self.confirmButton.setText(_translate("ReportItemDialog", "Confirm"))
        self.departmentEdit.setPlaceholderText(_translate("ReportItemDialog", "e.g. BSCS"))
        self.label_13.setText(_translate("ReportItemDialog", "Person Details"))
        self.lastNameEdit.setPlaceholderText(_translate("ReportItemDialog", "Last Name"))
        self.backButton.setText(_translate("ReportItemDialog", "B"))
        self.label.setText(_translate("ReportItemDialog", "Report an Item"))
        self.label_12.setText(_translate("ReportItemDialog", "Department"))
        self.labelImagePreview.setText(_translate("ReportItemDialog", "TextLabel"))
        self.uploadImageButton.setText(_translate("ReportItemDialog", "Upload"))
