# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'surrenderItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SurrenderItemDialog(object):
    def setupUi(self, SurrenderItemDialog):
        SurrenderItemDialog.setObjectName("SurrenderItemDialog")
        SurrenderItemDialog.resize(602, 682)
        self.stackedWidget = QtWidgets.QStackedWidget(SurrenderItemDialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 601, 681))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.itemPage = QtWidgets.QWidget()
        self.itemPage.setObjectName("itemPage")
        self.label_2 = QtWidgets.QLabel(self.itemPage)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.itemNameEdit = QtWidgets.QLineEdit(self.itemPage)
        self.itemNameEdit.setGeometry(QtCore.QRect(20, 140, 301, 41))
        self.itemNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.itemNameEdit.setText("")
        self.itemNameEdit.setObjectName("itemNameEdit")
        self.label_3 = QtWidgets.QLabel(self.itemPage)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.locationFoundEdit = QtWidgets.QLineEdit(self.itemPage)
        self.locationFoundEdit.setGeometry(QtCore.QRect(320, 220, 271, 41))
        self.locationFoundEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.locationFoundEdit.setObjectName("locationFoundEdit")
        self.label_5 = QtWidgets.QLabel(self.itemPage)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.itemPage)
        self.label_6.setGeometry(QtCore.QRect(330, 190, 211, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.descriptionEdit = QtWidgets.QLineEdit(self.itemPage)
        self.descriptionEdit.setGeometry(QtCore.QRect(20, 300, 561, 61))
        self.descriptionEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.descriptionEdit.setText("")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.label_7 = QtWidgets.QLabel(self.itemPage)
        self.label_7.setGeometry(QtCore.QRect(30, 270, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.nextButton = QtWidgets.QPushButton(self.itemPage)
        self.nextButton.setGeometry(QtCore.QRect(369, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.nextButton.setObjectName("nextButton")
        self.cancelButton = QtWidgets.QPushButton(self.itemPage)
        self.cancelButton.setGeometry(QtCore.QRect(20, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton.setObjectName("cancelButton")
        self.frame_2 = QtWidgets.QFrame(self.itemPage)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 611, 80))
        self.frame_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(190, 0, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.dateFoundEdit = QtWidgets.QDateTimeEdit(self.itemPage)
        self.dateFoundEdit.setGeometry(QtCore.QRect(20, 220, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateFoundEdit.setFont(font)
        self.dateFoundEdit.setCalendarPopup(True)
        self.dateFoundEdit.setObjectName("dateFoundEdit")
        self.label_14 = QtWidgets.QLabel(self.itemPage)
        self.label_14.setGeometry(QtCore.QRect(380, 110, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.comboBox_2 = QtWidgets.QComboBox(self.itemPage)
        self.comboBox_2.setGeometry(QtCore.QRect(370, 140, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.itemImageButton = QtWidgets.QPushButton(self.itemPage)
        self.itemImageButton.setGeometry(QtCore.QRect(470, 470, 101, 31))
        self.itemImageButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.itemImageButton.setObjectName("itemImageButton")
        self.itemImagePreview = QtWidgets.QLabel(self.itemPage)
        self.itemImagePreview.setGeometry(QtCore.QRect(30, 400, 431, 191))
        self.itemImagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.itemImagePreview.setObjectName("itemImagePreview")
        self.label_15 = QtWidgets.QLabel(self.itemPage)
        self.label_15.setGeometry(QtCore.QRect(30, 370, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.itemPage)
        self.personPage = QtWidgets.QWidget()
        self.personPage.setObjectName("personPage")
        self.label_8 = QtWidgets.QLabel(self.personPage)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.phoneNumberEdit = QtWidgets.QLineEdit(self.personPage)
        self.phoneNumberEdit.setGeometry(QtCore.QRect(21, 280, 271, 41))
        self.phoneNumberEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.phoneNumberEdit.setObjectName("phoneNumberEdit")
        self.cancelButton_2 = QtWidgets.QPushButton(self.personPage)
        self.cancelButton_2.setGeometry(QtCore.QRect(21, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton_2.setFont(font)
        self.cancelButton_2.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton_2.setObjectName("cancelButton_2")
        self.label_9 = QtWidgets.QLabel(self.personPage)
        self.label_9.setGeometry(QtCore.QRect(31, 160, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.personPage)
        self.label_10.setGeometry(QtCore.QRect(31, 250, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.firstNameEdit = QtWidgets.QLineEdit(self.personPage)
        self.firstNameEdit.setGeometry(QtCore.QRect(20, 190, 271, 41))
        self.firstNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.confirmButton = QtWidgets.QPushButton(self.personPage)
        self.confirmButton.setGeometry(QtCore.QRect(370, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.confirmButton.setObjectName("confirmButton")
        self.label_12 = QtWidgets.QLabel(self.personPage)
        self.label_12.setGeometry(QtCore.QRect(320, 250, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.personPage)
        self.label_13.setGeometry(QtCore.QRect(21, 90, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lastNameEdit = QtWidgets.QLineEdit(self.personPage)
        self.lastNameEdit.setGeometry(QtCore.QRect(310, 190, 271, 41))
        self.lastNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.frame = QtWidgets.QFrame(self.personPage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 611, 80))
        self.frame.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 0, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setGeometry(QtCore.QRect(20, 20, 60, 31))
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    padding: 4px 6px;\n"
"    font-size: 10pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: gray;\n"
"}")
        self.backButton.setObjectName("backButton")
        self.departmentEdit_2 = QtWidgets.QLineEdit(self.personPage)
        self.departmentEdit_2.setGeometry(QtCore.QRect(310, 280, 271, 41))
        self.departmentEdit_2.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.departmentEdit_2.setObjectName("departmentEdit_2")
        self.proofImagePreview = QtWidgets.QLabel(self.personPage)
        self.proofImagePreview.setGeometry(QtCore.QRect(20, 360, 441, 231))
        self.proofImagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.proofImagePreview.setObjectName("proofImagePreview")
        self.proofImageButton = QtWidgets.QPushButton(self.personPage)
        self.proofImageButton.setGeometry(QtCore.QRect(470, 470, 101, 31))
        self.proofImageButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.proofImageButton.setObjectName("proofImageButton")
        self.stackedWidget.addWidget(self.personPage)

        self.retranslateUi(SurrenderItemDialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SurrenderItemDialog)

    def retranslateUi(self, SurrenderItemDialog):
        _translate = QtCore.QCoreApplication.translate
        SurrenderItemDialog.setWindowTitle(_translate("SurrenderItemDialog", "Dialog"))
        self.label_2.setText(_translate("SurrenderItemDialog", "Item Details"))
        self.label_3.setText(_translate("SurrenderItemDialog", "Name"))
        self.label_5.setText(_translate("SurrenderItemDialog", "Date Found"))
        self.label_6.setText(_translate("SurrenderItemDialog", "Location Found"))
        self.label_7.setText(_translate("SurrenderItemDialog", "Description"))
        self.nextButton.setText(_translate("SurrenderItemDialog", "Next"))
        self.cancelButton.setText(_translate("SurrenderItemDialog", "Cancel"))
        self.label_11.setText(_translate("SurrenderItemDialog", "Surrender an Item"))
        self.label_14.setText(_translate("SurrenderItemDialog", "Category"))
        self.comboBox_2.setItemText(0, _translate("SurrenderItemDialog", "Electronics"))
        self.comboBox_2.setItemText(1, _translate("SurrenderItemDialog", "School Supplies"))
        self.comboBox_2.setItemText(2, _translate("SurrenderItemDialog", "Clothing and Accessories"))
        self.comboBox_2.setItemText(3, _translate("SurrenderItemDialog", "I.D Cards"))
        self.comboBox_2.setItemText(4, _translate("SurrenderItemDialog", "Wallets "))
        self.comboBox_2.setItemText(5, _translate("SurrenderItemDialog", "Keys"))
        self.comboBox_2.setItemText(6, _translate("SurrenderItemDialog", "Personal Items"))
        self.comboBox_2.setItemText(7, _translate("SurrenderItemDialog", "Others"))
        self.itemImageButton.setText(_translate("SurrenderItemDialog", "Upload "))
        self.itemImagePreview.setText(_translate("SurrenderItemDialog", "No Image Selected"))
        self.label_15.setText(_translate("SurrenderItemDialog", "Item Image"))
        self.label_8.setText(_translate("SurrenderItemDialog", "Proof ID"))
        self.phoneNumberEdit.setPlaceholderText(_translate("SurrenderItemDialog", "e.g. 09123456789"))
        self.cancelButton_2.setText(_translate("SurrenderItemDialog", "Cancel"))
        self.label_9.setText(_translate("SurrenderItemDialog", "Name"))
        self.label_10.setText(_translate("SurrenderItemDialog", "Phone Number"))
        self.firstNameEdit.setPlaceholderText(_translate("SurrenderItemDialog", "First Name"))
        self.confirmButton.setText(_translate("SurrenderItemDialog", "Confirm"))
        self.label_12.setText(_translate("SurrenderItemDialog", "Department"))
        self.label_13.setText(_translate("SurrenderItemDialog", "Personal Details"))
        self.lastNameEdit.setPlaceholderText(_translate("SurrenderItemDialog", "Last Name"))
        self.label.setText(_translate("SurrenderItemDialog", "Surrender an Item"))
        self.backButton.setText(_translate("SurrenderItemDialog", "Back"))
        self.departmentEdit_2.setPlaceholderText(_translate("SurrenderItemDialog", "e.g. BSCS"))
        self.proofImagePreview.setText(_translate("SurrenderItemDialog", "No Image Selected"))
        self.proofImageButton.setText(_translate("SurrenderItemDialog", "Upload"))
