# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateItemDialog(object):
    def setupUi(self, UpdateItemDialog):
        UpdateItemDialog.setObjectName("UpdateItemDialog")
        UpdateItemDialog.resize(600, 682)
        self.categoryComboBox = QtWidgets.QComboBox(UpdateItemDialog)
        self.categoryComboBox.setGeometry(QtCore.QRect(310, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.categoryComboBox.setFont(font)
        self.categoryComboBox.setStyleSheet("QComboBox {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(UpdateItemDialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 460, 101, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.pushButton.setObjectName("pushButton")
        self.cancelButton = QtWidgets.QPushButton(UpdateItemDialog)
        self.cancelButton.setGeometry(QtCore.QRect(20, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"        border: 1px solid;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: lightgray;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: gray;\n"
"    }")
        self.cancelButton.setObjectName("cancelButton")
        self.itemNameEdit = QtWidgets.QLineEdit(UpdateItemDialog)
        self.itemNameEdit.setGeometry(QtCore.QRect(20, 160, 271, 41))
        self.itemNameEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.itemNameEdit.setText("")
        self.itemNameEdit.setObjectName("itemNameEdit")
        self.label_2 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(UpdateItemDialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 611, 80))
        self.frame_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(180, 0, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_14.setGeometry(QtCore.QRect(320, 130, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.descriptionEdit = QtWidgets.QLineEdit(UpdateItemDialog)
        self.descriptionEdit.setGeometry(QtCore.QRect(20, 320, 561, 41))
        self.descriptionEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.descriptionEdit.setText("")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.label_7 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_7.setGeometry(QtCore.QRect(30, 290, 191, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_15.setGeometry(QtCore.QRect(30, 370, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.locationEdit = QtWidgets.QLineEdit(UpdateItemDialog)
        self.locationEdit.setGeometry(QtCore.QRect(310, 240, 271, 41))
        self.locationEdit.setStyleSheet("QLineEdit {\n"
"        border: 2px solid #ccc;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.locationEdit.setObjectName("locationEdit")
        self.itemImagePreview = QtWidgets.QLabel(UpdateItemDialog)
        self.itemImagePreview.setGeometry(QtCore.QRect(30, 400, 411, 171))
        self.itemImagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.itemImagePreview.setObjectName("itemImagePreview")
        self.confirmButton = QtWidgets.QPushButton(UpdateItemDialog)
        self.confirmButton.setGeometry(QtCore.QRect(369, 610, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("QPushButton {\n"
"        background-color: rgb(170, 0, 0);\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #800000;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #4d0000;\n"
"    }")
        self.confirmButton.setObjectName("confirmButton")
        self.label_6 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_6.setGeometry(QtCore.QRect(320, 210, 211, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(UpdateItemDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 240, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_3 = QtWidgets.QLabel(UpdateItemDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 80, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(UpdateItemDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateItemDialog)

    def retranslateUi(self, UpdateItemDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateItemDialog.setWindowTitle(_translate("UpdateItemDialog", "Dialog"))
        self.categoryComboBox.setItemText(0, _translate("UpdateItemDialog", "Electronics"))
        self.categoryComboBox.setItemText(1, _translate("UpdateItemDialog", "School Supplies"))
        self.categoryComboBox.setItemText(2, _translate("UpdateItemDialog", "Clothing and Accessories"))
        self.categoryComboBox.setItemText(3, _translate("UpdateItemDialog", "I.D Cards"))
        self.categoryComboBox.setItemText(4, _translate("UpdateItemDialog", "Wallets "))
        self.categoryComboBox.setItemText(5, _translate("UpdateItemDialog", "Keys"))
        self.categoryComboBox.setItemText(6, _translate("UpdateItemDialog", "Personal Items"))
        self.categoryComboBox.setItemText(7, _translate("UpdateItemDialog", "Others"))
        self.pushButton.setText(_translate("UpdateItemDialog", "Upload "))
        self.cancelButton.setText(_translate("UpdateItemDialog", "Cancel"))
        self.label_2.setText(_translate("UpdateItemDialog", "Item Details"))
        self.label_11.setText(_translate("UpdateItemDialog", "Update an Item"))
        self.label_14.setText(_translate("UpdateItemDialog", "Category"))
        self.label_5.setText(_translate("UpdateItemDialog", "Date"))
        self.label_7.setText(_translate("UpdateItemDialog", "Description"))
        self.label_15.setText(_translate("UpdateItemDialog", "Item Image"))
        self.itemImagePreview.setText(_translate("UpdateItemDialog", "No Image Selected"))
        self.confirmButton.setText(_translate("UpdateItemDialog", "Confirm"))
        self.label_6.setText(_translate("UpdateItemDialog", "Update Location"))
        self.label_3.setText(_translate("UpdateItemDialog", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateItemDialog = QtWidgets.QDialog()
    ui = Ui_UpdateItemDialog()
    ui.setupUi(UpdateItemDialog)
    UpdateItemDialog.show()
    sys.exit(app.exec_())
